auth:
  jwt:
    secret: ${JWT_SECRET:}
  api:
    id: ${CLIENT_ID:}
    secret: ${CLIENT_SECRET:}
    state: ${STATE:}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD:}
    url: ${MYSQL_URL:}
    username: ${MYSQL_USERNAME:}
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: update