name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          java-package: jdk

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build --stacktrace
        shell: bash

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker Image Build
        run: docker build --build-arg DEPENDENCY=build/dependency -t dohyeon5626/ahreview .

      - name: Upload to DockerHub
        run: docker push dohyeon5626/ahreview
